name: MingW (Msys2)

on:
  push:
    branches:
      - debug

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
            { msystem: MINGW64 },
            { msystem: MINGW64 },
        ]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p

      - name: Build
        shell: msys2 {0}
        run: |
          cmake -B build_dir -DCMAKE_BUILD_TYPE=Release -D_GNU_SOURCE -G "MSYS Makefiles"
          cmake --build build_dir
